Docs to migrate REST APIs to Twirp
twitchtv/twirp pull request #347
Opened 2022-01-15 06:36 UTC by marioizquierdo

Even though the migration process is a case-by-case scenario, it is still useful to have some basic guidelines for the recommended approach. If the community has useful tools that could be used in some cases, we could add links to those tools in this page too. If there are other guides for migrating from gRPC, Swagger and others, we could add those sections on this document later too.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-21 02:12 UTC, marioizquierdo commented on CONTRIBUTING.md
> +4.  Navigate to http://localhost:3000/twirp.
This is the only part I updated in this document. The way to install docusaurus changed a little bit and the docs no longer apply. Everything else was prettify in my editor "fixing" the markdown

2022-01-25 18:11 UTC, wmatveyenko requested changes

2022-01-25 18:11 UTC, wmatveyenko commented on docs/migrate_to_twirp.md
> +Twirp APIs are restricted to requests in the form `POST [<prefix>]/[<package>.]<Service>/<Method>` (see [Routing and Serialization](routing.md)). That limitation is what allows to build simple and co
Change "what allows to build" to "what allows building"

2022-01-25 18:11 UTC, wmatveyenko commented on docs/migrate_to_twirp.md
> +5.  Make sure to track stats about API endpoint usage, so you can see the traffic being migrated to the new endpoints. Using [hooks or interceptors](hooks.md), or HTTP [middleware](mux.md) can be use
remove comma in "), or HTTP"

2022-01-25 18:11 UTC, wmatveyenko commented on docs/migrate_to_twirp.md
> +6.  The API callers (upstream services) need to import the new Twirp client and update their calls to use the new Twirp API. Here is where making the new API similar to the old one will be the most u
Change "Here is where making the new API similar to the old one will be the most useful." to "This is why making the new API similar to the old one is useful."

2022-02-02 23:25 UTC, marioizquierdo commented
@wmatveyenko thanks for the review. I addressed the docs with the suggestions, and took the chance to give it another edit pass.

2022-02-07 21:27 UTC, wmatveyenko approved these changes

2022-02-07 21:28 UTC, merged